### ISSUE TITLE
masked and rsv data is not currently supported

### ISSUE THREAD

**Issue by rianrian1027** [Copterdoctor/SwiftWAMP#1]
I'm getting the issue when connecting to the endpoint.

`ERROR: Optional(Starscream.HTTPUpgradeError.notAnUpgrade(426))
ERROR: Optional(Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002))
`
Do you have any idea?

**Comment by rianrian1027** [comment]
FYI, I tested connection and subscription in javascript and also I was able to connect using URLSession:

        let urlSession = URLSession(configuration: .default)
        let webSocketTask = urlSession.webSocketTask(with: URL(string: "wss://my-endpoint")!, protocols: ["wamp"])
        
        webSocketTask.receive { (result) in
            switch result {
            case .failure(let error):
                print("Error in receiving message: \(error)")
            case .success(let message):
                switch message {
                case .string(let text):
                    print("Received text: \(text)")
                case .data(let data):
                    print("Received data: \(data)")
                default:
                    break
                }
            }
        }

        webSocketTask.resume()

**Comment by Copterdoctor** [comment]
What wamp router are you trying to connect to? I've only tested this with Crossbar since it's what I'm using on my current project.

The issue with Starscream that appears to manifest for a variety of reasons. [websocket disconnected: masked and rsv data is not currently supported](https://github.com/daltoniam/Starscream/issues?q=is%3Aissue+rsv)

Theres an open issue regarding code 1002.
